name: Custom Input Nextflow Workflow

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
        nextflow: ['latest-edge', 'latest-stable' ]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
          java-version: ${{ matrix.java }}

    - name: Setup Nextflow ${{ matrix.nextflow }}
      uses: nf-core/setup-nextflow@v1
      with:
          version: "${{ matrix.nextflow }}"

    - name: Run Nextflow Workflow with Custom Inputs
      run: |
        echo "mhoroi" > greetings.txt
        echo "shona" > languages.txt
        nextflow run hello-world.nf
